resolver: lts-18.0
extra-deps:
  - acc-0.1.3
  - attoparsec-data-1.0.5.1
  - attoparsec-time-1.0.1.1
  - domain-0.1.1
  - domain-core-0.1
  - domain-optics-0.1
  - th-lego-0.2.3
  - yaml-unscrambler-0.1.0.2
  - git: https://github.com/nikita-volkov/xml-unscrambler
    commit: !!str 402ca30b4d98a8e4ab96fc46bc1127af6bcd1b8e
