resolver: nightly-2021-07-01
extra-deps:
  - acc-0.1.3
  - attoparsec-data-1.0.5.2
  - attoparsec-time-1.0.1.2
  - domain-0.1.1.2
  - domain-core-0.1
  - domain-optics-0.1
  - template-haskell-compat-v0208-0.1.6
  - th-lego-0.2.3
  - yaml-unscrambler-0.1.0.3
  - git: https://github.com/nikita-volkov/xml-parser
    commit: !!str 80c5571e7c5e451f64bb9ba5030000a8c8d47e4f
