on: [push]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v2
        with:
          extra-args: -o -XAllowAmbiguousTypes -o -XApplicativeDo -o -XBangPatterns -o -XBinaryLiterals -o -XBlockArguments -o -XConstraintKinds -o -XDataKinds -o -XDefaultSignatures -o -XDeriveAnyClass -o -XDeriveDataTypeable -o -XDeriveFoldable -o -XDeriveFunctor -o -XDeriveGeneric -o -XDeriveLift -o -XDeriveTraversable -o -XDerivingStrategies -o -XDerivingVia -o -XDuplicateRecordFields -o -XEmptyCase -o -XEmptyDataDecls -o -XExplicitNamespaces -o -XFlexibleContexts -o -XFlexibleInstances -o -XFunctionalDependencies -o -XGADTs -o -XGeneralizedNewtypeDeriving -o -XHexFloatLiterals -o -XInstanceSigs -o -XLambdaCase -o -XLiberalTypeSynonyms -o -XMagicHash -o -XMultiParamTypeClasses -o -XMultiWayIf -o -XNamedFieldPuns -o -XNoImplicitPrelude -o -XNoMonomorphismRestriction -o -XNumericUnderscores -o -XOverloadedLabels -o -XOverloadedStrings -o -XParallelListComp -o -XPatternGuards -o -XPatternSynonyms -o -XQuasiQuotes -o -XRankNTypes -o -XRecordWildCards -o -XScopedTypeVariables -o -XStandaloneDeriving -o -XStrictData -o -XTemplateHaskell -o -XTupleSections -o -XTypeApplications -o -XTypeFamilies -o -XTypeOperators -o -XTypeSynonymInstances -o -XUndecidableInstances -o -XViewPatterns

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: haskell/actions/setup@v1.2.1
        name: Setup
        with:
          enable-stack: true
          stack-version: 2.7.1
          stack-no-global: true

      - uses: actions/cache@v2.1.6
        name: Cache
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml', 'stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: ${{ runner.os }}-stack-

      - name: Install dependencies
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build pedantically
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --ghc-options="-Werror -Wall -Wno-missing-signatures -Wno-name-shadowing -Wno-unused-do-bind -Wno-unused-top-binds"
        continue-on-error: true

      - name: Build
        run: stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test
